import Head from 'next/head'
import Image from 'next/image'
import MainView from 'common/components/views/mainview/index'
import {
  GET_CATEGORY_DATA,
  GET_PRODUCTS_CATEGORY_BY_ID,
} from "common/http/RequestData.js";

export const getServerSideProps = async () => {
  let productData = [];
  let catResponse = await GET_CATEGORY_DATA();
  if (catResponse) {

    productData = await Promise.all(catResponse.map(async cat  =>{
      return {
        categoryName: cat.name,
        products: await GET_PRODUCTS_CATEGORY_BY_ID(cat.id).then(res => {return res;})
      }
    }))
    let data = await productData;
    console.log(data);
  } else {
    console.warn(
      "Application may be not configured - Missing categories. Please check Admin panel."
    );
  }

  return {
    props: { data: productData },
  };
};
export default function Home({data}) {
  return (
    <div>
      <Head>
        <title>SportShop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <MainView products={data}/>
      </main>

      <footer >
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
