export const PRODUCT_DATA = [
  {
    id: "1",
    title: "Product Mens 1",
    price: "100",
    image: "https://picsum.photos/200/300",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sec pre urna aliquet nun",
    quantity: "25",
    category: "1",
    material: {"cotton": "95%", "elastan": "5%"},
    brand: "1",
    product_type: "1",
    size: ["XS", "S", "M", "L"],
  },
  {
    id: "2",
    title: "Product Womens 2",
    price: "200",
    image: "https://picsum.photos/200/300",
    description:
"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sec pre urna aliquet nun",
    quantity: "15",
    category: "2",
    material: { "cotton": "80%", "polyester": "20%"},
    brand: "1",
    product_type: "1",
    size: ["XS", "S", "M", "L"],
  },
  {
    id: "3",
    title: "Product Kids 3",
    price: "200",
    image: "https://picsum.photos/200/300",

    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sec pre urna aliquet nun",
    quantity: "10",
    category: "3",
    material:  {"cotton": "100%"},
    brand: "3",
    product_type: "1",
    size: ["XS", "S", "M", "L"],
  },
  {
    id: "4",
    title: "Product 4",
    price: "200",
    image: "https://picsum.photos/200/300",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sec pre urna aliquet nun",
    quantity: "10",
    category: "4",
    material: {"silk": "60%", "polyester": "40%"},
    brand: "4",
    product_type: "4",
    size: ["S", "M", "L"],
  },
  {
    id: "5",
    title: "Product Mens 5",
    price: "100",
    image: "https://picsum.photos/200/300",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sec pre urna aliquet nun",
    quantity: "15",
    category: "1",
    material: {"polyester": "80%", "cotton": "20%"},
    brand: "3",
    product_type: "2",
    size: ["M", "L"],
  },
  {
    id: "6",
    title: "Product Mens 6",
    price: "100",
    image: "https://picsum.photos/200/300",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sec pre urna aliquet nun",
    quantity: "15",
    category: "1",
    material: {"cotton": "70%", "polyester": "30%"},
    brand: "3",
    product_type: "2",
    size: ["M", "L"],
  },
  {
    id: "7",
    title: "Product Mens 7",
    price: "100",
    image: "https://picsum.photos/200/300",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sec pre urna aliquet nun",
    quantity: "15",
    category: "1",
    material: [{"cotton": "90%"}, {"elastan": "10%"}],
    brand: "3",
    product_type: "2",
    size: ["M", "L"],
  },
  {
    id: "8",
    title: "Product Womens 8",
    price: "100",
    image: "https://picsum.photos/200/300",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sec pre urna aliquet nun",
    quantity: "15",
    category: "2",
    material: {"cotton": "80%", "polyester": "20%"},
    brand: "3",
    product_type: "2",
    size: ["M", "L"],
  },
  {
    id: "9",
    title: "Product Kids 8",
    price: "100",
    image: "https://picsum.photos/200/300",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sec pre urna aliquet nun",
    quantity: "15",
    category: "3",
    material: {"cotton": "90%", "polyester": "10%"},
    brand: "3",
    product_type: "2",
    size: ["M", "L"],
  }
];
